"""add notification deduplication constraint

Revision ID: 0a0ebb890214
Revises: a37fe9a22f2f
Create Date: 2026-09-02 13:58:15.895028

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0a0ebb890214"
down_revision: str | Sequence[str] | None = "a37fe9a22f2f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_notification_user_type_reference",
        "notifications",
        ["user_id", "notification_type", "source_reference"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_notification_user_type_reference", "notifications", type_="unique"
    )
    # ### end Alembic commands ###
