"""create personalization tables

Revision ID: 2c70256d9209
Revises: 159fabef0ad0
Create Date: 2026-08-30 23:23:07.124080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c70256d9209'
down_revision: Union[str, Sequence[str], None] = '159fabef0ad0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_activity_preferences',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('activity_context', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'activity_context', name='uq_user_activity_context')
    )
    op.create_index(op.f('ix_user_activity_preferences_user_id'), 'user_activity_preferences', ['user_id'], unique=False)
    op.create_table('user_personas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('persona', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'persona', name='uq_user_persona')
    )
    op.create_index(op.f('ix_user_personas_user_id'), 'user_personas', ['user_id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('preferred_language', sa.String(length=10), nullable=False),
    sa.Column('temperature_unit', sa.String(length=20), nullable=False),
    sa.Column('preferred_start_hour', sa.Integer(), nullable=True),
    sa.Column('preferred_end_hour', sa.Integer(), nullable=True),
    sa.Column('official_alerts_enabled', sa.Boolean(), nullable=False),
    sa.Column('routine_alerts_enabled', sa.Boolean(), nullable=False),
    sa.Column('rain_alerts_enabled', sa.Boolean(), nullable=False),
    sa.Column('aqi_alerts_enabled', sa.Boolean(), nullable=False),
    sa.Column('daily_summary_enabled', sa.Boolean(), nullable=False),
    sa.Column('personalized_homepage_enabled', sa.Boolean(), nullable=False),
    sa.Column('routine_impact_enabled', sa.Boolean(), nullable=False),
    sa.Column('learning_enabled', sa.Boolean(), nullable=False),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_weather_interests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('interest', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('internal_weight', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'interest', name='uq_user_weather_interest')
    )
    op.create_index(op.f('ix_user_weather_interests_user_id'), 'user_weather_interests', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_weather_interests_user_id'), table_name='user_weather_interests')
    op.drop_table('user_weather_interests')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_user_personas_user_id'), table_name='user_personas')
    op.drop_table('user_personas')
    op.drop_index(op.f('ix_user_activity_preferences_user_id'), table_name='user_activity_preferences')
    op.drop_table('user_activity_preferences')
    # ### end Alembic commands ###
