"""create device registrations table

Revision ID: 40b0a5b8b27e
Revises: 0a0ebb890214
Create Date: 2026-09-02 16:31:20.993010

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "40b0a5b8b27e"
down_revision: str | Sequence[str] | None = "0a0ebb890214"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "device_registrations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("registration_id", sa.String(length=512), nullable=False),
        sa.Column("registration_type", sa.String(length=20), nullable=False),
        sa.Column("platform", sa.String(length=20), nullable=False),
        sa.Column("device_name", sa.String(length=120), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("registration_id", name="uq_device_registration_id"),
    )
    op.create_index(
        "ix_device_registrations_user_active",
        "device_registrations",
        ["user_id", "is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_device_registrations_user_id"),
        "device_registrations",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_device_registrations_user_id"), table_name="device_registrations"
    )
    op.drop_index(
        "ix_device_registrations_user_active", table_name="device_registrations"
    )
    op.drop_table("device_registrations")
    # ### end Alembic commands ###
