"""add user interactions

Revision ID: c6e007f24e8b
Revises: ef921dd3965d
Create Date: 2026-09-02 00:51:59.426143

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c6e007f24e8b"
down_revision: str | Sequence[str] | None = "ef921dd3965d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_interactions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("card_type", sa.String(length=50), nullable=False),
        sa.Column("action", sa.String(length=20), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.String(length=100), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_interactions_user_id"),
        "user_interactions",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        "ix_user_interactions_user_occurred_at",
        "user_interactions",
        ["user_id", "occurred_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_user_interactions_user_occurred_at", table_name="user_interactions"
    )
    op.drop_index(op.f("ix_user_interactions_user_id"), table_name="user_interactions")
    op.drop_table("user_interactions")
    # ### end Alembic commands ###
