"""create user routines table

Revision ID: c8899ccdabb2
Revises: 8b7c1e4a2d90
Create Date: 2026-09-01 17:50:22.837698

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c8899ccdabb2"
down_revision: str | Sequence[str] | None = "8b7c1e4a2d90"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_routines",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("saved_location_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("activity_context", sa.String(length=50), nullable=False),
        sa.Column("days_of_week", sa.JSON(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["saved_location_id"], ["saved_locations.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_routines_saved_location_id"),
        "user_routines",
        ["saved_location_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_routines_user_id"), "user_routines", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_routines_user_id"), table_name="user_routines")
    op.drop_index(
        op.f("ix_user_routines_saved_location_id"), table_name="user_routines"
    )
    op.drop_table("user_routines")
    # ### end Alembic commands ###
